#!/bin/bash

set -e

SRCDIR="$(dirname $0)"
TMPDIR="$(mktemp -d)"
DIR="${TMPDIR}"
TMP="${TMPDIR}"

PATH=/usr/sbin:/sbin:$PATH

export TMPDIR TMP PATH

cleanup() {
    echo Stopping varnishd and the agent
    [ -z "$varnishpid" ] || kill "$varnishpid" || true
    [ -z "$agentpid" ] || kill "$agentpid" || true
    echo Cleaning up
    rm -rf ${DIR}
}

trap 'cleanup' EXIT
echo DIR: ${DIR}
mkdir -p ${DIR}/vcl

head -c 16 /dev/urandom > "$DIR/secret"
VARNISH_PID="${DIR}/varnish.pid"
printf "Starting varnishd:\n\n"
varnishd -f "${SRCDIR}/data/boot.vcl" \
    -P "$VARNISH_PID" \
    -n "$DIR" \
    -p auto_restart=off \
    -a 127.0.0.1:0 \
    -T 127.0.0.1:0 \
    -S "$DIR/secret"
varnishpid="$(cat "$VARNISH_PID")"
VARNISH_PORT=$(varnishadm -n "$DIR" debug.listen_address | cut -d\  -f 2)
# XXX fix to find a free, not just a random port
AGENT_PORT=$(( 1024 + ( $RANDOM % 48000 ) ))

export VARNISH_PORT AGENT_PORT

printf "Starting agent:\n\n"
../src/varnish-agent -n ${DIR} -p ${DIR}/vcl/ -P ${DIR}/agent.pid -c "$AGENT_PORT"
agentpid=$(cat ${DIR}/agent.pid)
export N_ARG="-n ${DIR}"
echo "Settings: "
echo "  VARNISH_PORT: $VARNISH_PORT"
echo "  N_ARG: $N_ARG"
echo "  AGENT_PORT: $AGENT_PORT"
echo
echo Starting tests
cd "$SRCDIR"
./$1

# cleanup handled by trap
