#!/bin/bash

set -e

TMPDIR="$(mktemp -d -t vagent.XXXXXXXX)"
SRCDIR="$(dirname $0)/"

PATH=${PATH}:/usr/sbin:/sbin

ORIGPWD=$PWD

export TMPDIR PATH SRCDIR ORIGPWD

cd "$SRCDIR"
./$1

# cleanup handled by trap
